services:
    dns-server:
        logging:
          driver: syslog
          options:
            tag: dns-server
        image: hickorydns/hickory-dns:latest
        dns:
            - "10.222.222.1"
        hostname: dns.mail-server.intranet
        dns_search: mail-server.intranet.
        networks:
            mail_infra_network:
                ipv4_address: 10.222.222.1
                #ipv6_address: fd00:bee::1
        volumes:
            - ${HICKORY_DNS_NAMED_CONFIG:-./internal-dns/named.toml}:/etc/named.toml:ro
            - ./internal-dns/zones/:/var/named/zones/:ro
        environment:
            RUST_LOG: ${HICKORY_DNS_LOG_LEVEL:-info}
        healthcheck:
            test: "nslookup -type=A dns.mail-server.intranet 10.222.222.1 1>/dev/null"
            timeout: 3s
            retries: 10
            start_period: 2s

    mailserver:
        logging:
          driver: syslog
          options:
            tag: mailserver
        image: mailserver/docker-mailserver:15.0.0
        mem_limit: 4G
        mem_reservation: 2G
        restart: on-failure:40
        stop_grace_period: 1m
        dns:
            - "10.222.222.1"
        hostname: emails.mail-server.intranet
        dns_search: mail-server.intranet.
        networks:
            mail_infra_network:
                ipv4_address: 10.222.222.2
                #ipv6_address: fd00:bee::2
                aliases:
                  - ${OVERRIDE_HOSTNAME}
        ports:
            - "25:25"    # SMTP  (explicit TLS => STARTTLS)
            - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
            - "465:465"  # ESMTP (implicit TLS)
            - "587:587"  # ESMTP (explicit TLS => STARTTLS)
            - "993:993"  # IMAP4 (implicit TLS)
            - "110:110"  # POP3
            - "995:995"  # POP3 (with TLS)
            - "4190:4190" # Sieve filters
#            - "4177:4177" # Dovecot replication
            - "11334:11334" # Rspamd UI
#            - "11332:11332" # Rspamd proxy worker
        volumes:
            - ${MAIL_DATA_DIR}:/var/mail
            - ${MAIL_STATE_DIR}:/var/mail-state
            - ${MAIL_LOGS_DIR}:/var/log/mail
            - ${MAIL_CONFIGS_DIR}:/tmp/docker-mailserver/
            - ${USER_PATCHES_FILE:-./user-patches.sh}:/tmp/docker-mailserver/user-patches.sh:ro
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}_ecc/fullchain.cer:/etc/ssl/mail-server/server.cer:ro
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}_ecc/${DOMAIN_NAME}.key:/etc/ssl/mail-server/server.key:ro
            - ./rspamd/local.d/phishing.conf:/etc/rspamd/local.d/phishing.conf:ro
            - ./rspamd/local.d/mx_check.conf:/etc/rspamd/local.d/mx_check.conf:ro
            - ./rspamd/local.d/redis.conf:/etc/rspamd/local.d/redis.conf:ro
            # See: https://github.com/docker-mailserver/docker-mailserver/issues/2636
            - ./rspamd/local.d/dmarc-reports.conf:/etc/rspamd/local.d/dmarc-reports.conf:ro
            - ./rspamd/local.d/actions.conf:/etc/rspamd/local.d/actions.conf:ro
            - ./rspamd/local.d/milter_headers.conf:/etc/rspamd/local.d/milter_headers.conf:ro
            - ./rspamd/local.d/groups.conf:/etc/rspamd/local.d/groups.conf:ro
            - ./rspamd/local.d/multimap.conf:/etc/rspamd/local.d/multimap.conf:ro
            - ./rspamd/local.d/worker-controller.inc:/etc/rspamd/local.d/worker-controller.inc:ro
            - ./rspamd/local.d/dkim_signing.conf:/etc/rspamd/local.d/dkim_signing.conf:ro
            - ./rspamd/local.d/history_redis.conf:/etc/rspamd/local.d/history_redis.conf:ro
            - ./rspamd/local.d/rbl.conf:/etc/rspamd/local.d/rbl.conf:ro
            # maps
            - ./rspamd/maps.d/mx_whitelist.inc:/etc/rspamd/maps.d/mx_whitelist.inc:ro
            - ./rspamd/maps.d/local_wl_domain.map:/etc/rspamd/maps.d/local_wl_domain.map:ro
            - ./rspamd/maps.d/local_wl_from.map:/etc/rspamd/maps.d/local_wl_from.map:ro
            - ./cron/rspamd-learn:/etc/cron.d/rspamd-learn:ro
        environment:
            CONTAINER_NETWORK_V4: "10.222.222.0/28"
            CONTAINER_NETWORK_V6: "[fd00:bee::]/124"
            TZ: UTC
            OVERRIDE_HOSTNAME: ${OVERRIDE_HOSTNAME}
            ENABLE_MTA_STS: "1"
            ENABLE_RSPAMD: "1"
            ENABLE_RSPAMD_REDIS: "0"
            ENABLE_CLAMAV: "1"
            ENABLE_AMAVIS: "1"
            ENABLE_FAIL2BAN: "1"
            ENABLE_POSTGREY: "0"
            ENABLE_POP3: "1"
            ENABLE_IMAP: "1"
            ENABLE_MANAGESIEVE: "1"
            ENABLE_SASLAUTHD: "0"
            ENABLE_OPENDKIM: "1"
            ENABLE_OPENDMARC: "1"
            ENABLE_QUOTAS: "1"
            SPOOF_PROTECTION: "1"
            ENABLE_SPAMASSASSIN: "0"
            ENABLE_SPAMASSASSIN_KAM: "0"
            LOGROTATE_INTERVAL: "daily"
            ONE_DIR: "1"
            LOG_LEVEL: "${LOG_LEVEL:-warn}"
            ACCOUNT_PROVISIONER: "LDAP"
            RSPAMD_LEARN: "1"
            RSPAMD_GREYLISTING: "1"
            RSPAMD_CHECK_AUTHENTICATED: "0" # Do not spam check outgoing emails
            MOVE_SPAM_TO_JUNK: "1"
            # Now it's up to RSPAMD_GREYLISTING to greylist
            # POSTGREY_DELAY: "${POSTGREY_DELAY:-300}"
            # POSTGREY_AUTO_WHITELIST_CLIENTS: "1" # Defaults to 5
            LDAP_SERVER_HOST: "${LDAP_PROTOCOL:-ldaps}://10.10.10.5" # Must match the hostname for SSL verification
            DOVECOT_URIS: "${LDAP_PROTOCOL:-ldaps}://10.10.10.5" # Must match the hostname for SSL verification
            LDAP_SEARCH_BASE: "ou=people,${LDAP_BASE_DN}"
            LDAP_BIND_DN: ${LDAP_ADMIN_DN}
            LDAP_BIND_PW: ${LDAP_ADMIN_PASSWORD}
            LDAP_QUERY_FILTER_USER: "(&(mail=%s)(mailEnabled=TRUE))"
            LDAP_QUERY_FILTER_GROUP: "(&(mailGroupMember=%s)(mailEnabled=TRUE))"
            LDAP_QUERY_FILTER_ALIAS: "(|(&(mailAlias=%s)(objectClass=PostfixBookMailAccount))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))"
            LDAP_QUERY_FILTER_DOMAIN: "(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailAccount)))"
            DOVECOT_PASS_FILTER: "(&(objectClass=PostfixBookMailAccount)(mail=%n@%d))"
            DOVECOT_USER_FILTER: "(&(objectClass=PostfixBookMailAccount)(mail=%n@%d))"
            DOVECOT_DEFAULT_PASS_SCHEME: "SSHA256"
            TLS_LEVEL: "intermediate"
            POSTFIX_MESSAGE_SIZE_LIMIT: "100000000"

            # Replication
            DOVECOT_ITERATE_ATTRS: "mail=user"
            DOVECOT_ITERATE_FILTER: "(objectClass=PostfixBookMailAccount)"

            SSL_TYPE: "manual"
            SSL_CERT_PATH: "/etc/ssl/mail-server/server.cer"
            SSL_KEY_PATH: "/etc/ssl/mail-server/server.key"
            # Daily report & reporting
            # See: https://sources.debian.org/src/cron/3.0pl1-163/debian/patches/features/Add-MAILFROM-environment-variable.patch/?hl=93#L93
            MAILFROM: "${CRON_MAILFROM:-$POSTMASTER_ADDRESS}"
            MAILTO: "${CRON_MAILTO:-$POSTMASTER_ADDRESS}"
            POSTMASTER_ADDRESS: "${POSTMASTER_ADDRESS}"
            VIRUS_ADMIN_EMAIL: "${VIRUS_ADMIN_EMAIL}"
            PFLOGSUMM_RECIPIENT: "${PFLOGSUMM_RECIPIENT}"
            PFLOGSUMM_TRIGGER: daily_cron
            LOGWATCH_INTERVAL: daily
            LOGWATCH_RECIPIENT: "${LOGWATCH_RECIPIENT}"
            # Fail2ban config to allow IPs to make failed attempts
            FAIL2BAN_IGNORE_IPS: "${FAIL2BAN_IGNORE_IPS}"
            FAIL2BAN_DST_EMAIL: "${FAIL2BAN_DST_EMAIL}"
            FAIL2BAN_SENDER_EMAIL: "${FAIL2BAN_SENDER_EMAIL}"
            FAIL2BAN_SENDER_NAME: "${FAIL2BAN_SENDER_NAME}"

            # Fail2ban reporting
            FAIL2BAN_BLOCKLIST_DE_API_KEY: "${FAIL2BAN_BLOCKLIST_DE_API_KEY:-}"
            FAIL2BAN_BLOCKLIST_DE_EMAIL: "${FAIL2BAN_BLOCKLIST_DE_EMAIL:-}"
            FAIL2BAN_IPTHREAT_API_KEY: "${FAIL2BAN_IPTHREAT_API_KEY:-}"
            FAIL2BAN_IPTHREAT_SYSTEM_NAME: "${FAIL2BAN_IPTHREAT_SYSTEM_NAME:-}"
            FAIL2BAN_ABUSEIPDB_API_KEY: "${FAIL2BAN_ABUSEIPDB_API_KEY:-}"

        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 10
            start_period: 20s
        depends_on:
            dns-server:
                condition: service_healthy
        # netcap: https://stackoverflow.com/a/35485119/5155484
        # getpcaps <pid>
        # https://book.hacktricks.xyz/linux-hardening/privilege-escalation/linux-capabilities
        cap_add:
            - NET_ADMIN # fail2ban, spamd
            - NET_RAW # spamd
            - NET_BIND_SERVICE # dovecot, spamd
            - CHOWN # dovecot, spamd
            - DAC_OVERRIDE # dovecot, spamd
            - SYS_CHROOT # dovecot, spamd
            - SETUID # dovecot, spamd
            - SETGID # dovecot, spamd
            - KILL # dovecot, spamd
            - FOWNER # spamd
            - FSETID # spamd
            - SETPCAP # spamd
            - MKNOD # spamd
            - AUDIT_WRITE # spamd
            - SETFCAP # spamd
        security_opt:
          - no-new-privileges:true
        cap_drop:
            - ALL

networks:
    mail_infra_network:
        name: infrastructure_mail_infra_network
        #enable_ipv6: true
        ipam:
            driver: default
            # See: __add_to_postfix_mynetworks in user-patches
            config:
                - subnet: 10.222.222.0/28
                  # 14 hosts
                  ip_range: 10.222.222.0/28
                  gateway: 10.222.222.14

                #- subnet: fd00:bee::/124
                  # 16 hosts
                  # From fd00:bee:: to fd00:bee::f
                  #gateway: fd00:bee::f
