#!/bin/sh -eu

ME=$(realpath $(dirname $0))

if [ ! -f $ME/.env ]; then
    echo "Missing env: $ME/.env"
    exit 1
fi

# Load up .env
set -o allexport
# Source the file
. $ME/.env
set +o allexport

cd $ME

if [ -z "${NO_VERBOSE:-}" ]; then
    printf 'Running in: %s\n' "${DOCKER_PROJECT_NAME}"
fi

docker compose -p ${DOCKER_PROJECT_NAME} $@
