name: run full tests
on: [push]

permissions:
  contents: read

jobs:
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker compose version
              run: docker compose version
            - name: create temp folder
              run: make create-temp-env
            - name: setup for tests
              run: make setup-test
            - name: run docker-test
              run: make run-test
            - name: teardown tests
              run: make cleanup-test
