name: Publish Docker image

permissions:
    contents: read
    packages: write

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to GitHub registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build image
              run: make docker-build
              env:
                  DOCKER_BUILDKIT: 1
                  PLATFORM: linux/amd64
                  IMAGE_TAG: ghcr.io/datacenters-network/mails/mailserver
                  ACTION: push

            - name: Test image
              run: make docker-test
              env:
                  IMAGE_TAG: ghcr.io/datacenters-network/mails/mailserver
